name: vvweb
channels:
  - conda-forge
  - bioconda
dependencies:
  - pip
  - python=3.8
  - sqlite
  - protobuf
  - mysql-connector-python
  # - pysam
  - pyliftover>=0.3
  - numpy
  - httplib2>=0.9.0
  - configparser>=3.5.0
  - requests
  - weasyprint
  - cairo
  - pango
