name: vvweb
channels:
  - conda-forge
  - bioconda
dependencies:
  - pip
  - python=3.6
  - sqlite=3.28
  - protobuf=3.5.1
  - mysql-connector-python
  - pysam
  - pyliftover>=0.3
  - numpy
  - httplib2>=0.9.0
  - configparser>=3.5.0
  - requests
