name: vvweb_v2
channels:
  - conda-forge
  - bioconda
dependencies:
  - pip
  - python=3.10
  - sqlite
  - mysql-connector-python
  - configparser
  - certifi
  - cffi
  - curl
  - fontconfig==2.13.1
  - freetype
  - icu
  - krb5
  - ncurses
  - numpy
  - protobuf
  - pyliftover
  - pysam
  - readline
  - libffi

