name: vvweb
channels:
  - conda-forge
  - defaults
dependencies:
  - celery
  - django
  - pip
  - python=3.6
  - sqlite=3.28
  - sqlparse=0.3
  - pip:
    - django-celery-results
    - django-widget-tweaks
    - variantValidator>=1.0.0
    - django-cookie-law
