name: vvweb
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - celery
  - django
  - pip
  - python=3.6
  - sqlite=3.28
  - sqlparse=0.3
  - pysam
  - pip:
    - django-celery-results
    - django-widget-tweaks
    - git+https://github.com/openvar/VariantValidator@master#egg=VariantValidator
    - django-cookie-law
    - django-allauth
    - django-recaptcha
    - django-countries
    - django-celery-beat
