name: vvweb_v2
channels:
  - conda-forge
  - bioconda
dependencies:
  - pip
  - python=3.12.11
  - cffi
  - curl
  - fontconfig
  - freetype
  - icu
  - krb5
  - ncurses
  - readline
  - libffi
  - libprotobuf
  - glib
  - pango

