"""
Django settings for VVweb project.

Generated by 'django-admin startproject' using Django 2.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
from datetime import timedelta
import sys
import logging
from logging import handlers
from configparser import ConfigParser
from VariantValidator import settings as vv_settings

# Change settings based on config
config = ConfigParser()
config.read(vv_settings.CONFIG_DIR)

# Setup logging logic
if config['logging'].getboolean('log') is True:

    # ---- console ----
    vv_console_raw = config['logging'].get('console', fallback='INFO')

    if vv_console_raw.lower() in ('false', '0', 'no', 'off'):
        vv_logging_console_level = False
    else:
        vv_logging_console_level = vv_console_raw.upper()

    # ---- file ----
    vv_file_raw = config['logging'].get('file', fallback='ERROR')

    if vv_file_raw.lower() in ('false', '0', 'no', 'off'):
        vv_logging_file_level = False
    else:
        vv_logging_file_level = vv_file_raw.upper()

    # ---- optional path ----
    try:
        vv_logging_file_path = config['logging']['file_path']
    except KeyError:
        vv_logging_file_path = os.getcwd()

else:
    vv_logging_console_level = False
    vv_logging_file_level = False

# Refuse connections in test mode
if "pytest" in sys.argv:
    raise RuntimeError(
        "FATAL: pytest attempted with production settings"
    )

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False
DEBUG = TEMPLATE_DEBUG = False

ALLOWED_HOSTS = [
    'www182.lamp.le.ac.uk',
    'www180.lamp.le.ac.uk',
    'www512.lamp.le.ac.uk',
    'variantvalidator.org',
    'www.variantvalidator.org',
    '127.0.0.1',
    '127.0.0.1:8000'
]

# CSRF trusted origins for HTTPS requests (especially under Apache + mod_wsgi)
CSRF_TRUSTED_ORIGINS = [
    'https://www182.lamp.le.ac.uk',
    'https://www180.lamp.le.ac.uk',
    'https://www512.lamp.le.ac.uk',
    'https://variantvalidator.org',
    'https://www.variantvalidator.org',
]

# Ensures Django respects forwarded Host headers when behind reverse proxy
USE_X_FORWARDED_HOST = True

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.humanize',
    'web',
    'widget_tweaks',
    'django_celery_results',
    'cookielaw',
    'allauth',
    'allauth.account',
    'userprofiles.apps.UserprofilesConfig',
    'verification',
    'django_recaptcha',
    'django_countries',
    'django_celery_beat',
]


MIDDLEWARE = [
    # 1) Security + required Django stack
    'django.middleware.security.SecurityMiddleware',
    "web.middleware.SiteRedirectMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',

    # 2) Authentication
    'django.contrib.auth.middleware.AuthenticationMiddleware',

    # 3) Your enforcement middleware (runs while authenticated)
    'verification.middleware.TierEnforcementMiddleware',
    "userprofiles.middleware.PrimaryEmailResetMiddleware",

    # 4) Django messages + clickjacking
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # 5) Allauth middleware
    'allauth.account.middleware.AccountMiddleware',

    # 6) Your post‑Allauth login bounce interceptor
    'verification.middleware_postallauth.PostAllauthLoginRedirectFix',
]



ROOT_URLCONF = 'VVweb.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.template.context_processors.media',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'web.context_processors.account_status',
            ],
        },
    },
]

WSGI_APPLICATION = 'VVweb.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'vvweb',
    }
}

SITE_ID = 4

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = (

    "userprofiles.auth_backends.ProfileAwareModelBackend",
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
)

LOGIN_REDIRECT_URL = 'profile-home'

# ==============================
# Django Allauth Configuration
# ==============================

# Allow login using either email or username
ACCOUNT_LOGIN_METHODS = {'email', 'username'}

# Signup fields: all required
ACCOUNT_SIGNUP_FIELDS = ['email*', 'username*', 'password1*', 'password2*']

# IMPORTANT:
# Let users LOG IN even if their email is not verified yet.
# Your own middleware + StrictLoginView handle verification flow.
ACCOUNT_EMAIL_VERIFICATION = "optional"        # was "mandatory"
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_PRESERVE_EMAIL_CASE = False

# Do NOT auto-send email confirmation on login or signup.
# Your system sends email only when the user clicks "Send".
ACCOUNT_EMAIL_CONFIRMATION_AUTO_SEND = False
ACCOUNT_EMAIL_CONFIRMATION_AUTO_SEND_ON_LOGIN = False

# Do NOT auto-log-in users after confirming email (you prefer login first).
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = False

# Custom signup form
ACCOUNT_FORMS = {
    'signup': 'web.forms.UpdatedSignUpForm',
}

# Custom display name function
ACCOUNT_USER_DISPLAY = 'userprofiles.utils.show_user'


# -------------------------------------------------------------------
# SESSION MANAGEMENT (prevents stale-session redirect loops)
# -------------------------------------------------------------------

# Two weeks — standard for authenticated sessions
SESSION_COOKIE_AGE = 1209600

# Refresh session expiry on every request (keeps sessions fresh)
SESSION_SAVE_EVERY_REQUEST = True

# Do NOT expire session on browser close
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# IMPORTANT:
# When you change authentication flow, middleware order,
# login logic, or Allauth behavior, bump this cookie name.
# It forces all users to receive a *fresh* session and
# prevents ERR_TOO_MANY_REDIRECTS after deployments.
SESSION_COOKIE_NAME = "vvsession_v2"

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATIC_URL = '/static/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# Celery settings
CELERY_BROKER_URL = 'amqp://guest:guest@localhost:5672//'
CELERY_RESULT_BACKEND = 'django-db'
CELERY_CACHE_BACKEND = 'django-cache'

# Celery serialization settings
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

# Keep Celery task results for 30 days
CELERY_RESULT_EXPIRES = timedelta(days=30)

# Email settings
DEFAULT_FROM_EMAIL = 'admin@variantValidator.org'
EMAIL_SUBJECT_PREFIX = '[VVWeb] '
SERVER_EMAIL = 'admin@variantValidator.org'
ACCOUNT_EMAIL_SUBJECT_PREFIX = '[VVWeb] '

# Local email debugging configuration
if DEBUG:
    # Use MailHog/MailCatcher or similar at localhost:1025
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST = "localhost"
    EMAIL_PORT = 1025
    EMAIL_USE_TLS = False
    EMAIL_HOST_USER = ""
    EMAIL_HOST_PASSWORD = ""

    # IMPORTANT: set a valid default sender for dev
    DEFAULT_FROM_EMAIL = "dev-noreply@variantvalidator.local"

# For VCF to HGVS conversion
MAX_VCF = 20000

COUNTRIES_FIRST = ['GB', 'US']

# settings.py (or settings_logging.py)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,

    # --------------------------------------------------
    # Formatters
    # --------------------------------------------------
    "formatters": {
        "verbose": {
            "format": "%(asctime)s %(levelname)-8s %(name)s:%(lineno)d %(message)s",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
        "console": {
            "format": "[%(asctime)s] %(levelname)-8s %(name)s %(message)s",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
    },

    # --------------------------------------------------
    # Handlers
    # --------------------------------------------------
    "handlers": {
        # Existing VV handlers (unchanged)
        "vv_console": {
            "class": "logging.StreamHandler",
            "level": vv_logging_console_level,
            "formatter": "console",
        },
        "vv_file": {
            "class": "logging.handlers.RotatingFileHandler",
            "level": vv_logging_file_level,
            "filename": os.path.join(BASE_DIR, "logs", "VariantValidator.log"),
            "maxBytes": 5_000_000,
            "backupCount": 5,
            "formatter": "verbose",
        },

        # VVweb file handler
        "vvweb_console": {
            "class": "logging.StreamHandler",
            "level": vv_logging_console_level,
            "formatter": "console",
        },

        "vvweb_file": {
            "class": "logging.handlers.RotatingFileHandler",
            "level": vv_logging_file_level,
            "filename": os.path.join(BASE_DIR, "logs", "VVweb.log"),
            "maxBytes": 5_000_000,
            "backupCount": 5,
            "formatter": "verbose",
        },

        # Django default error handling (unchanged)
        "django_console": {
            "class": "logging.StreamHandler",
            "level": "ERROR",
            "formatter": "console",
        },
    },

    # --------------------------------------------------
    # Loggers
    # --------------------------------------------------
    "loggers": {
        # VariantValidator stays owned by VV
        "VariantValidator": {
            "handlers": ["vv_console", "vv_file"],
            "level": vv_logging_console_level,
            "propagate": False,
        },

        # VVweb application logger
        "VVweb": {
            "handlers": ["vvweb_console", "vvweb_file"],
            "level": vv_logging_console_level,
            "propagate": False,
        },

        # Let Django do its normal thing
        "django": {
            "handlers": ["django_console"],
            "level": "INFO",
            "propagate": True,
        },
    },
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Fair usage
# Free-tier default
DEFAULT_MONTHLY_VARIANT_ALLOWANCE = 20000
PRO_LIMIT = 100000
ENTERPRISE_LIMIT = 1000000
INSTITUTION_LIMIT = 1000000
COMMERCIAL_TRIAL_LIMIT = 0

try:
    from .local_settings import *
except ImportError as e:
    print(e)

# <LICENSE>
# Copyright (C) 2016-2026 VariantValidator Contributors
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
# </LICENSE>
