import pytest
from django.urls import reverse


@pytest.mark.django_db
def test_validate_view_processes_real_variant_end_to_end(
    client,
    standard_user,
    verify_email,
    submit_verification_form,
):
    """
    End-to-end test of validate() view using a real HGVS variant.

    This test implicitly exercises:
    - validator.validate()
    - raw.format_as_dict()
    - services.process_result()

    without mocking any internal service logic.
    """

    # ----------------------------------------------------------
    # Arrange: real logged-in user (no anonymous limits)
    # ----------------------------------------------------------
    client.force_login(standard_user)
    verify_email(standard_user)
    submit_verification_form()

    url = reverse("validate")

    variant = "NM_000088.4:c.589G>T"

    # ----------------------------------------------------------
    # Act: submit real validation
    # ----------------------------------------------------------
    response = client.post(
        url,
        data={
            "variant": variant,
            "genomebuild": "GRCh38",
            "refsource": "refseq",
            "transcripts": "mane_select",
        },
        follow=True,
    )

    # ----------------------------------------------------------
    # Assert: request succeeded
    # ----------------------------------------------------------
    assert response.status_code == 200
    assert "output" in response.context
    output = response.context["output"]

    # ----------------------------------------------------------
    # Assert: process_result() produced a valid structure
    # ----------------------------------------------------------
    assert output is not None
    assert "results" in output
    assert isinstance(output["results"], list)
    assert len(output["results"]) > 0

    # ----------------------------------------------------------
    # Assert: individual result integrity (process_result logic)
    # ----------------------------------------------------------
    result = output["results"][0]

    # Required keys added by process_result
    assert "id" in result
    assert "tx_ac" in result
    assert "safe_hgvs_trans" in result
    assert "latest" in result

    # Transcript accession should be derived correctly
    assert result["tx_ac"].startswith("NM_")

    # Should identify latest transcript version
    assert isinstance(result["latest"], bool)

    # safe_hgvs_trans is user-visible transcript description
    assert result["safe_hgvs_trans"]

    # Gene information should be present for COL1A1 variant
    assert result.get("gene_symbol") in ("COL1A1", None)

    # Input tracking preserved
    assert output["inputted"] == variant

@pytest.mark.django_db
def test_validate_view_generates_real_pdf_end_to_end(
    client,
    standard_user,
    verify_email,
    submit_verification_form,
):
    """
    End-to-end test of the validate() view in PDF mode.

    This test proves that:
    - A real HGVS variant is validated
    - services.process_result() runs
    - pdf_results.html is rendered
    - render_to_pdf() executes (WeasyPrint)
    - A real PDF byte stream is returned
    """

    # ----------------------------------------------------------
    # Arrange: authenticated user (no anonymous limits)
    # ----------------------------------------------------------
    client.force_login(standard_user)
    verify_email(standard_user)
    submit_verification_form()

    url = reverse("validate")

    variant = "NM_000088.4:c.589G>T"

    # ----------------------------------------------------------
    # Act: submit validation (PDF is generated by default)
    # ----------------------------------------------------------
    response = client.post(
        url,
        data={
            "variant": variant,
            "genomebuild": "GRCh38",
            "refsource": "refseq",
            "transcripts": "mane_select",
            # pdf_request intentionally omitted (default = PDF)
        },
        follow=False,
    )

    # ----------------------------------------------------------
    # Assert: HTTP + headers
    # ----------------------------------------------------------
    assert response.status_code == 200
    assert response["Content-Type"] == "application/pdf"

    assert "Content-Disposition" in response
    disposition = response["Content-Disposition"]
    assert "VariantValidator_report_" in disposition
    assert ".pdf" in disposition

    # ----------------------------------------------------------
    # Assert: response body is a real PDF
    # ----------------------------------------------------------
    pdf_bytes = response.content

    # WeasyPrint always produces a standard PDF header
    assert pdf_bytes.startswith(b"%PDF"), "Response is not a valid PDF file"

    # Sanity: prevent HTML or error text being returned instead
    assert b"<html" not in pdf_bytes[:500].lower()

    # Size sanity check: real PDFs are not tiny
    # (prevents false positives like an error message wrapped as PDF)
    assert len(pdf_bytes) > 5_000, "Generated PDF is unexpectedly small"

# <LICENSE>
# Copyright (C) 2016-2026 VariantValidator Contributors
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
# </LICENSE>
